### ISSUE TITLE
Error launching color picker

### ISSUE THREAD

**Issue by ysavr** [Dhaval2404/ColorPicker#11]
Hello I was trying to use the ColorPicker, but when the app is running and the Dialog is opening the app crash with the following error:

java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/databinding/DataBinderMapperImpl;
        at androidx.databinding.DataBindingUtil.<clinit>(DataBindingUtil.java:32)
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:95)
        at com.github.dhaval2404.colorpicker.adapter.MaterialColorPickerAdapter.bindAdapter(MaterialColorPickerAdapter.kt:48)
        at com.github.dhaval2404.colorpicker.adapter.MaterialColorPickerAdapter.onCreateViewHolder(MaterialColorPickerAdapter.kt:57)
        at com.github.dhaval2404.colorpicker.adapter.MaterialColorPickerAdapter.onCreateViewHolder(MaterialColorPickerAdapter.kt:20)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at com.google.android.flexbox.FlexboxLayoutManager.getFlexItemAt(FlexboxLayoutManager.java:456)
        at com.google.android.flexbox.FlexboxLayoutManager.getReorderedFlexItemAt(FlexboxLayoutManager.java:474)
        at com.google.android.flexbox.FlexboxHelper.calculateFlexLines(FlexboxHelper.java:427)
        at com.google.android.flexbox.FlexboxHelper.calculateHorizontalFlexLines(FlexboxHelper.java:247)
        at com.google.android.flexbox.FlexboxLayoutManager.updateFlexLines(FlexboxLayoutManager.java:953)
        at com.google.android.flexbox.FlexboxLayoutManager.onLayoutChildren(FlexboxLayoutManager.java:729)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
        at android.view.View.measure(View.java:19762)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6122)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19762)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6122)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19762)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6122)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19762)
        at androidx.appcompat.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:134)
        at androidx.appcompat.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:64)
        at android.view.View.measure(View.java:19762)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6122)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
        at android.view.View.measure(View.java:19762)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6122)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19762)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6122)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19762)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6122)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19762)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6122)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:690)
        at android.view.View.measure(View.java:19762)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2315)

**Comment by Dhaval2404** [comment]
@yusufsafrudin Can you please tell me which version of ColorPicker you are using in the app?

If not v1.2.1. Please consider upgrading the lib
`implementation 'com.github.dhaval2404:colorpicker:1.2.1'
`

**Comment by Dhaval2404** [comment]
Looking at the stack trace it looks like you're using **v1.0.0**. Please consider upgrading to **v1.2.1**. There is no breaking change in this. It should work fine. In case you got any error do let me know.

**Comment by ysavr** [comment]
thank you, it's work for me
